ci_script implementation

diff --git a/ci_framework/roles/os_must_gather/tasks/main.yml b/ci_framework/roles/os_must_gather/tasks/main.yml
--- a/ci_framework/roles/os_must_gather/tasks/main.yml
+++ b/ci_framework/roles/os_must_gather/tasks/main.yml
@@ -22,7 +22,9 @@
     - logs
 
 - name: Check for oc command
-  ansible.builtin.command: command -v oc
+  ci_script:
+    output_dir: "{{ cifmw_os_must_gather_output_dir }}/artifacts"
+    script: command -v oc
   environment:
     PATH: "{{ cifmw_path | default(ansible_env.PATH) }}"
   register: oc_installed
@@ -38,8 +40,9 @@
       environment:
         KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
         PATH: "{{ cifmw_path }}"
-      ansible.builtin.shell:
-        cmd: >-
+      ci_script:
+        output_dir: "{{ cifmw_os_must_gather_output_dir }}/artifacts"
+        script: |
           oc adm must-gather --image {{ cifmw_os_must_gather_image }}
           --timeout {{ cifmw_os_must_gather_timeout }}
           --host-network={{ cifmw_os_must_gather_host_network }}
@@ -50,9 +53,10 @@
       environment:
         KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
         PATH: "{{ cifmw_path }}"
-      ansible.builtin.shell: |
-        mkdir -p {{ cifmw_os_must_gather_output_dir }}/logs/oc_inspect
-        for ns in openstack-operators openstack baremetal-operator-system openshift-machine-api cert-manager openshift-nmstate metallb-system; do
-          oc adm inspect namespace/"${ns}" --dest-dir={{ cifmw_os_must_gather_output_dir }}/logs/oc_inspect || echo "Error getting logs from ${ns}"
-          oc get pods -n ${ns} > ${ns}_pods.txt
-        done
+      ci_script:
+        output_dir: "{{ cifmw_os_must_gather_output_dir }}/artifacts"
+        script: |
+          mkdir -p {{ cifmw_os_must_gather_output_dir }}/logs/oc_inspect
+          for ns in openstack-operators openstack baremetal-operator-system openshift-machine-api cert-manager openshift-nmstate metallb-system; do
+            oc adm inspect namespace/"${ns}" --dest-dir={{ cifmw_os_must_gather_output_dir }}/logs/oc_inspect || echo "Error getting logs from ${ns}"
+          done
