Force the source file to exist for the ping test.

diff --git a/roles/update/templates/l3_agent_start_ping.sh.j2 b/roles/update/templates/l3_agent_start_ping.sh.j2
--- a/roles/update/templates/l3_agent_start_ping.sh.j2
+++ b/roles/update/templates/l3_agent_start_ping.sh.j2
@@ -9,12 +9,8 @@ PING_LOG="{{ cifmw_update_artifacts_basedir }}/ping_results_$(date +%Y%m%d%H%M%S
 if [ -f "${INSTANCE_FILE}" ]; then
     source "${INSTANCE_FILE}"
 else
-    {% if workload_sriov|default(false) | bool %}
-    echo export VM_IP=$(openstack server list -f json | jq -r -c '.[0]["Networks"]' | cut -d"=" -f2) > {{ working_dir }}/vm_ip.sh
-    {% else %}
-    echo export VM_IP=$(openstack floating ip list -f json | jq -r -c '.[] | select(.Port) | .["Floating IP Address"]' | head -1) > {{ working_dir }}/vm_ip.sh
-    {% endif %}
-    source {{ working_dir }}/vm_ip.sh
+    echo "Cannot find the instance file information (${INSTANCE_FILE})"
+    exit 1
 fi
 
 # NOTE: the &>> is necessary as if we don't redirect both
