Fix bashhate errors

diff --git a/scripts/create_osp_instance b/scripts/create_osp_instance
--- a/scripts/create_osp_instance
+++ b/scripts/create_osp_instance
@@ -31,27 +31,27 @@ NC='\033[0m' # No Color
 ##----------------------------------------------------------------------------
 
 # this function works in case of long running command  with verbous mode
-progress_indicator(){
-  local aux_file=$1 # warning: file content is mutable
-  local command=$2  # long running command
+progress_indicator() {
+    local aux_file=$1 # warning: file content is mutable
+    local command=$2  # long running command
 
-  touch "$aux_file"  # create the auxiliary file if it doesn't exist
-  truncate -s 0 "$aux_file"  # delete content (if existing)
+    touch "$aux_file"         # create the auxiliary file if it doesn't exist
+    truncate -s 0 "$aux_file" # delete content (if existing)
 
-  previous_size=$(stat -c %s "$aux_file")
+    previous_size=$(stat -c %s "$aux_file")
 
-  # run the long running command in the background
-  eval $command &> "$aux_file" &
-  background_pid=$!
+    # run the long running command in the background
+    eval $command &>"$aux_file" &
+    background_pid=$!
 
-  while kill -0 "$background_pid" >/dev/null 2>&1; do
-    current_size=$(stat -c %s "$aux_file")
-    if [[ $current_size -gt $previous_size ]]; then
-      echo -n "#"  # print "#" if the file size has increased
-      previous_size=$current_size  # update previous size
-    fi
-    sleep 1  # wait for 1 second before checking again
-  done
+    while kill -0 "$background_pid" >/dev/null 2>&1; do
+        current_size=$(stat -c %s "$aux_file")
+        if [[ $current_size -gt $previous_size ]]; then
+            echo -n "#"                 # print "#" if the file size has increased
+            previous_size=$current_size # update previous size
+        fi
+        sleep 1 # wait for 1 second before checking again
+    done
 }
 
 # long_running_command=(find / -exec ls -ld '{}' \; -exec sleep 1 \;)
@@ -63,44 +63,42 @@ progress_indicator(){
 #    1 to indicate that Quit option was selected
 #    0 otherwize
 interactive_cmd_assembly() {
-  local options_list=$1
-  local step=$2
+    local options_list=$1
+    local step=$2
 
-  # Split the into an array of options
-  IFS=$'\n' read -rd '' -a options <<< "$options_list"
+    # Split the into an array of options
+    IFS=$'\n' read -rd '' -a options <<<"$options_list"
 
-  # Add the "Quit" option
-  options+=("Quit")
+    # Add the "Quit" option
+    options+=("Quit")
 
-  # Create the interactive menu
-  PS3="Select "$step": "
-  select opt in "${options[@]}"
-  do
-    case $opt in
-      "Quit")
-        return 1
-        ;;
-      *)
-        echo "You selected: $opt"
+    # Create the interactive menu
+    PS3="Select "$step": "
+    select opt in "${options[@]}"; do
+        case $opt in
+        "Quit")
+            return 1
+            ;;
+        *)
+            echo "You selected: $opt"
 
-        # choose flavor
-        if [[ $step == "flavor" ]]; then
-          read -r flavor _ <<< "$opt"
-          echo "Result: "$flavor
-        fi
+            # choose flavor
+            if [[ $step == "flavor" ]]; then
+                read -r flavor _ <<<"$opt"
+                echo "Result: "$flavor
+            fi
 
-        # choose Centos image
-        if [[ $step == "image" ]]; then
-          read -r image _ <<< "$opt"
-          echo "Result: "$image
-        fi
+            # choose Centos image
+            if [[ $step == "image" ]]; then
+                read -r image _ <<<"$opt"
+                echo "Result: "$image
+            fi
 
-        return 0
-        ;;
-    esac
-  done
+            return 0
+            ;;
+        esac
+    done
 }
-
 
 check_ssh_reachable() {
     local ssh_port=22
@@ -108,27 +106,26 @@ check_ssh_reachable() {
     return $?
 }
 
-wait_for_sshd(){
-  # Set the maximum number of retries
-  local max_retries=30
+wait_for_sshd() {
+    # Set the maximum number of retries
+    local max_retries=30
 
-  # Set the delay between retries (in seconds)
-  local retry_delay=5
+    # Set the delay between retries (in seconds)
+    local retry_delay=5
 
-  # Loop to check SSH reachability
-  retry_count=0
-  while ! check_ssh_reachable; do
-      retry_count=$((retry_count+1))
-      if [ $retry_count -gt $max_retries ]; then
-          echo "${RED}SSH is not reachable after $max_retries retries${NC}"
-          exit 1
-      fi
-      echo "SSH is not reachable. Retrying in $retry_delay seconds..."
-      sleep $retry_delay
-  done
+    # Loop to check SSH reachability
+    retry_count=0
+    while ! check_ssh_reachable; do
+        retry_count=$((retry_count + 1))
+        if [ $retry_count -gt $max_retries ]; then
+            echo "${RED}SSH is not reachable after $max_retries retries${NC}"
+            exit 1
+        fi
+        echo "SSH is not reachable. Retrying in $retry_delay seconds..."
+        sleep $retry_delay
+    done
 
 }
-
 
 ##----------------------------------------------------------------------------
 ## entry point----------------------------------------------------------------
@@ -158,25 +155,23 @@ source $expanded_path
 # Recommended requirements
 cpu_cores=12
 ram_capacity=32768 #MiB
-disk_capacity=100 #GiB
-
+disk_capacity=100  #GiB
 
 ##----------------------------------------------------------------------------
 # Capture flavors as an output of the command addressing recommended
 # requirements and build a menu
 echo -e "${BLUE}Selecting an instance flavor${NC}"
-flavors=$(openstack flavor list -c Name -c RAM -c Disk -c VCPUs -f value | \
-          awk -v cpu_cores=$cpu_cores \
-              -v ram_capacity="$ram_capacity" \
-              -v disk_capacity=$disk_capacity \
-              '$2>ram_capacity && $3>disk_capacity && $4>cpu_cores')
+flavors=$(openstack flavor list -c Name -c RAM -c Disk -c VCPUs -f value |
+    awk -v cpu_cores=$cpu_cores \
+        -v ram_capacity="$ram_capacity" \
+        -v disk_capacity=$disk_capacity \
+        '$2>ram_capacity && $3>disk_capacity && $4>cpu_cores')
 output=$(interactive_cmd_assembly "$flavors" "flavor")
 if [ $? == 1 ]; then
-  echo "Exiting..."
-  exit 0
+    echo "Exiting..."
+    exit 0
 fi
 flavor_name=$(echo "$output" | grep "Result:" | awk '{print $2}')
-
 
 ##----------------------------------------------------------------------------
 # Capture Centos images as an output of the command and build a menu
@@ -188,7 +183,7 @@ progress_indicator "$aux_file" "$long_running_command"
 echo "" # jump to the next line
 pattern="ID[[:space:]]*|[[:space:]]*Name[[:space:]]*|[[:space:]]*Status"
 output=$(sed -n "/$pattern/,\$p" "$aux_file" | grep -i centos | awk '{ print $4; }')
-images=$(echo "$output" | tail -n +1)  #  everything after the pattern
+images=$(echo "$output" | tail -n +1) #  everything after the pattern
 output=$(interactive_cmd_assembly "$images" "image")
 image_name=$(echo "$output" | grep "Result:" | awk '{print $2}')
 
@@ -196,12 +191,12 @@ image_name=$(echo "$output" | grep "Result:" | awk '{print $2}')
 # Select less congested network
 echo -e "${BLUE}Choosing the less congested network${NC}"
 long_running_command="openstack network list --external -c Name -f value | \
-                      xargs -r -n1 openstack ip availability show -f json"
+                        xargs -r -n1 openstack ip availability show -f json"
 progress_indicator "$aux_file" "$long_running_command"
 echo "" # jump to the next line
-network_name=$(cat $aux_file |  \
-               jq -r '.id as $network_id | .subnet_ip_availability[] | select(.ip_version == 4) | "\(.total_ips - .used_ips) \($network_id)"' |  \
-               sort -nr | head -n1 |  awk ' {{print  $NF}}' | xargs -n1 openstack network show  -c name -f value)
+network_name=$(cat $aux_file |
+    jq -r '.id as $network_id | .subnet_ip_availability[] | select(.ip_version == 4) | "\(.total_ips - .used_ips) \($network_id)"' |
+    sort -nr | head -n1 | awk ' {{print  $NF}}' | xargs -n1 openstack network show -c name -f value)
 
 ##----------------------------------------------------------------------------
 # Importing publik key to the cloud
@@ -221,18 +216,17 @@ existing_keypair=$(openstack keypair show -f value -c name $keypair_name 2>/dev/
 if [[ -n $existing_keypair ]]; then
     echo -e "${RED}Warning: Key pair with the name $keypair_name already exists${NC}"
 else
-  # Import the key pair
-  openstack keypair create --public-key $pubkey_path $keypair_name
+    # Import the key pair
+    openstack keypair create --public-key $pubkey_path $keypair_name
 fi
-
 
 ##----------------------------------------------------------------------------
 # Create a vm with values selected peviously
 instanse_name="e2e-edpm-deployment"
 echo -e "${BLUE}Creating $instanse_name instance${NC}"
 output=$(openstack server create --flavor $flavor_name --image $image_name \
-                   --key-name $keypair_name --network $network_name \
-                   --security-group default $instanse_name)
+    --key-name $keypair_name --network $network_name \
+    --security-group default $instanse_name)
 if [ $? -ne 0 ]; then
     echo -e "${RED}Error: Failed to create an instance${NC}"
     exit 1
@@ -246,17 +240,16 @@ start_time=$(date +%s)
 echo -e "${BLUE}Waiting for instance to become ACTIVE${NC}"
 
 # Loop until the instance status becomes ACTIVE or timeout occurs
-while :
-do
+while :; do
     # Get the current status
     status=$(openstack server show $instance_id -f value -c status)
 
     if [[ $status == "ACTIVE" ]]; then
-      # Instance is active, get the IP address and print it
-      instance_ip=$(openstack server show $instance_id -f json -c addresses | \
-           jq -r --arg netname "$network_name" '.addresses | to_entries[] | select(.key == $netname) | .value[0]')
-      echo "" # jump to the next line
-      break
+        # Instance is active, get the IP address and print it
+        instance_ip=$(openstack server show $instance_id -f json -c addresses |
+            jq -r --arg netname "$network_name" '.addresses | to_entries[] | select(.key == $netname) | .value[0]')
+        echo "" # jump to the next line
+        break
     fi
 
     # Check if more than 2 minutes have passed
@@ -271,7 +264,6 @@ do
     echo -n "#" # progress indicator
     sleep 1
 done
-
 
 ##----------------------------------------------------------------------------
 # Commands to execute on the instance
@@ -291,19 +283,19 @@ commands=(
 # Iterate over the commands and execute the progress_indicator function
 installed_all_packages=true
 for cmd in "${commands[@]}"; do
-   $cmd # or use "progress_indicator "aux_file" "$cmd"" to hide the output
+    $cmd # or use "progress_indicator "aux_file" "$cmd"" to hide the output
 
-   if [ $? -ne 0 ]; then
-    echo -e "${RED}Error: Failed to perform $cmd${NC}"
-    installed_all_packages=false
-  fi
+    if [ $? -ne 0 ]; then
+        echo -e "${RED}Error: Failed to perform $cmd${NC}"
+        installed_all_packages=false
+    fi
 done
 
 ##----------------------------------------------------------------------------
 # How to connect to the instance
 if [[ $installed_all_packages == true ]]; then
-  echo -e "${BLUE}Congrats! The instance is ready:${NC}"
+    echo -e "${BLUE}Congrats! The instance is ready:${NC}"
 else
-  echo -e "${RED}Install packages manulally:${NC}"
+    echo -e "${RED}Install packages manulally:${NC}"
 fi
 echo "  ssh cloud-user@$instance_ip -i $pubkey_path"
